function Hd = filter_downsampling
%FILTER_DOWNSAMPLING Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.4 and the Signal Processing Toolbox 6.22.
% Generated on: 18-May-2015 11:17:39

Fpass = 1800000;   % Passband Frequency
Fstop = 2700000;   % Stopband Frequency
Apass = 1;         % Passband Ripple (dB)
Astop = 60;        % Stopband Attenuation (dB)
Fs    = 44100000;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'equiripple', ...
    'MinOrder', 'any', ...
    'StopbandShape', 'flat');

set(Hd, 'Arithmetic', 'single');
